### ISSUE TITLE
Pip3 already install paramiko ,but run Django project still ImportError: No module named paramiko

### ISSUE THREAD

**Issue by luckygogreen** [luckygogreen/AccessGateway#8]
system Ubuntu18.04 ,i remove the python 3.6.5 ,and install the python 3.8.0
after that ,everyting gone be fine ,but only paramiko not work 
$ pip list :
```
Package             Version
------------------- -------
amqp                2.5.2  
asgiref             3.2.3  
bcrypt              3.1.7  
billiard            3.6.2.0
celery              4.4.0  
cffi                1.14.0 
cryptography        2.8    
Django              3.0.3  
django-filter       2.2.0  
djangorestframework 3.11.0 
kombu               4.6.7  
Markdown            3.2    
paramiko            2.7.1  
pip                 20.0.2 
pycparser           2.19   
PyNaCl              1.3.0  
pytz                2019.3 
setuptools          41.2.0 
six                 1.14.0 
sqlparse            0.3.0  
vine                1.3.0  
```
when i start the project 
$python3 manage.py runserver 0.0.0.0:9002
error message.
```
Traceback (most recent call last):
  File "/home/DjangoPorject/AccessGateway/backend_task/run_task.py", line 3, in <module>
    import paramiko
ImportError: No module named paramiko
```

**Comment by luckygogreen** [comment]
Detials error
`Traceback (most recent call last):
  File "/home/DjangoPorject/AccessGateway/backend_task/run_task.py", line 94, in <module>
    django.setup()
  File "/usr/local/python3/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/python3/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/python3/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/python3/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'AccessGateway'
`

**Comment by luckygogreen** [comment]
check sys.path ,
you will find a lot of python2.7 
so just make python is default
`update-alternatives --install /usr/bin/python python /usr/bin/python3 1`
